### ISSUE TITLE
Pas de code pour le chapitre 5 ?

### ISSUE THREAD

**Issue by Bendrox** [kayhman/ENIBookGradientBoosting#1]

**Comment by kayhman** [comment]
Bonjour @Bendrox,

Merci pour le retour. En effet, le code n'avait pas été mis en ligne. Voilà qui est chose faite.

Si vous avez lu le livre, je suis preneur d'une revue sur amazon ou d'un post sur les réseaux :) 

Merci !

**Comment by Bendrox** [comment]
Merci votre le retour. Je n'y manquerai pas , le livre est intéressant (notamment le chapitre 5!)
La seule chose qui manque c'est des exemples avec des problématiques de classification supervisée. Avant d'écrire le commentaire je voulais savoir si vous aviez éventuellement un exemple de code  de classification supervisée sur la partie ch5_xgb_with_xgb.py. Merci!

**Comment by kayhman** [comment]
Bonjour,

Je n'ai pas de code sur le partie classification issue du livre. Par contre
j'ai écrit un article sur les détails de la gestion de la classification
par xgboost.
Vous pouvez le trouver ici :
https://towardsdatascience.com/native-support-of-categories-in-xgboost-how-does-it-work-d359096bd003

Merci pour la revue. Je compte sur vous :)

Cordialement
